# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: coding until the tea hours of dawn
description: > # this means to ignore newlines until "baseurl:"
  A blog about computers and tea.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://resurrexit.github.io
twitter_username: jekyllrb
github_username:  resurrexit

# Build settings
markdown: kramdown

# Disqus comments
disqus_short_name: "resurrexit"
disqus_show_comment_count: false
